### ISSUE TITLE
Technical reports genre

### ISSUE THREAD

**Issue by jvine** [sul-dlss/solrmarc-sw#106]
See SW-1506 for spec

This may need to be part of sw_genre field in stanford-mods;  we need to know if there is MODS data for tech reports, and if so, what does it look like.  @shelleydoljack  @hannahfrost

**Comment by hannahfrost** [comment]
'<typeOfResource>text'
'<genre authority="marcgt">technical report'

That's how we do it in Hydrus

**Comment by lmcglohon** [comment]
@jvine How should this display - Technical report, Technical reports, Technical Report, or Technical Reports?

**Comment by jvine** [comment]
Technical report

Facet values are singular; general SUL style is sentence case.

**Comment by lmcglohon** [comment]
example ckeys - 11453369 through 11453377
