### ISSUE TITLE
SDR Library facet

### ISSUE THREAD

**Issue by jvine** [sul-dlss/solrmarc-sw#107]
If there is an 856 with purl.stanford.edu then it should be indexed in the SDR library facet. 

SW-1463

**Comment by lmcglohon** [comment]
Already done with Stanford Sync 
https://github.com/sul-dlss/solrmarc-sw/blob/c0b9f9a9872c86b4cd7358dd7c3e7e8cfe3444fe/stanford-sw/src/edu/stanford/StanfordIndexer.java#L2128-#L2143
@jvine @jkeck @aeschylus

**Comment by lmcglohon** [comment]
I believe this was done with the following pull request:
https://github.com/sul-dlss/solrmarc-sw/pull/82

**Comment by lmcglohon** [comment]
Maybe not complete -
