### ISSUE TITLE
MODS: BCE dates and Extent for coin collection

### ISSUE THREAD

**Issue by jvine** [sul-dlss/solrmarc-sw#111]
This issue will be moved (copied) to the approp repo, eg. discovery-indexer or whatever uses the stanford-mods methods.   See lib/searchworks/origin_info.rb -- stanford-mods can now handle these dates.

Question:  is there any MARC data that has these dates?  Who would know?  @shelleydoljack

**Comment by shelleydoljack** [comment]
SW-1455
SW-1453

**Comment by ndushay** [comment]
Need to use new pub dates in stanford-mods recent release.   See lib/searchworks/origin_info.rb

**Comment by jvine** [comment]
related to #1140

**Comment by ndushay** [comment]
@jvine  @jkeck  so we're ok with the date slider going negative if the values are correct (e.g. roman coins)?   Or will the date slider field still need to screen out negative numbers?

**Comment by jvine** [comment]
do the negative numbers correspond to the actual BCE years? like will we go from 1 directly to -1, or will there be a zero that confuses things?

**Comment by ndushay** [comment]
negative numbers correspond with BCE years.  so  9 BCE  is  -9.

**Comment by jvine** [comment]
then i think it makes sense to show them in the date slider.

**Comment by ndushay** [comment]
@jkeck does the date slider work with negative numbers, if they are actually the correct negative numbers?

**Comment by ndushay** [comment]
"The primary use case of this plugin is for 'year' data, but it should work for any integer field. It may not work right for negative numbers, however. "    from Description section here:  https://github.com/projectblacklight/blacklight_range_limit.

ugh.

**Comment by ndushay** [comment]
Question: is there any MARC data that has these dates? Who would know?  @shelleydoljack ?

**Comment by ndushay** [comment]
sul-dlss/sw-indexer-service#59   addresses  the Date part of this for MODS data, except for doing the actual indexing.

@jvine  Is there still a question on MARC data for early dates?  Or can this issue be closed?

**Comment by jvine** [comment]
@ndushay not afaik. :+1: for closure.
