### ISSUE TITLE
Add PAGE-AR items to Art & Architecture library

### ISSUE THREAD

**Issue by jvine** [sul-dlss/solrmarc-sw#120]
Part of #101 still to complete:

Items with library = SAL3 and location = PAGE-AR should be given two library facet values:

- SAL3 (off-campus storage) <- they are currently getting this
- **Art & Architecture (Bowes)**

Yes, this means these items will appear to be in 2 libraries when they physically exist in one. There are about 250 of them.

**Comment by lmcglohon** [comment]
@jvine This has already been implemented - https://github.com/sul-dlss/solrmarc-sw/blob/5f0a0ae12a74ca1128372b49fd9bcef3ff061823/stanford-sw/src/edu/stanford/StanfordIndexer.java#L1619-#L1627
So I think we can close this.

**Comment by jvine** [comment]
@lmcglohon the code should be PAGE-AR, not PAGE_AR. And I don't know what the internal field names are, but the code is a location, not an item type. So my guess is that the code may be looking at the wrong place for the wrong value.

**Comment by lmcglohon** [comment]
@jvine thank you for noticing - instead of _.  Which location should I be looking in? Home location or current location or both?  Can you provide the ckey you were using to look for so I can see what the data looks like?

**Comment by jvine** [comment]
home location
example ckey 1111725
