### ISSUE TITLE
Hoover call numbers starting with XX

### ISSUE THREAD

**Issue by lmcglohon** [sul-dlss/solrmarc-sw#121]
https://jirasul.stanford.edu/jira/browse/SW-1583

**Comment by lmcglohon** [comment]
Many of Hoover Archives' collections have call number that start with XX (e.g. XX066 Box 9). SearchWorks is treating these as "no call number", just like a Symphony system-assigned call number, which is in this form: XX(123456.1). In this particular record SW is displaying 420 "no call number" in the list of items and in the request form. Since the actual call number is not given, I don't see how a user can request the right box. 

Message sent from: https://searchworks.stanford.edu/view/4086148

**Comment by lmcglohon** [comment]
If the call number starts with XX and the library is HV-ARCHIVE, do not skip the call number. Instead use the XX call number as a valid call number for use to request.

**Comment by ndushay** [comment]
from sul-dlss/SearchWorks#1148:

"

In general, we replace call numbers with the pattern XX(1234.5) with "no call number". These are typically on-order items.

However, Hoover Archives has legit collection call numbers that begin with XX - e.g. XX066.
https://searchworks.stanford.edu/view/4086148

We need to display these collection call numbers in order for the items to be requestable.

These numbers should also be searchable in the call number index. XX066 gets no results.

SW-1583"
