### ISSUE TITLE
See if we can run solrmarc against the sw-preview-prod collection in sul-solr

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss/solrmarc-sw#164]
Overall, want to know can solrmarc run with a solr index in sul-solr (solrcloud)?

**Comment by shelleydoljack** [comment]
We did this as part of an LD4P sprint: https://github.com/sul-dlss/solrmarc-sw/commit/0a30d25b180a667f0b80aa3c963899ff4e2c6066

**Comment by cbeer** [comment]
👏
