### ISSUE TITLE
Add docs for dev env setup from SW Performance Work Cycle Notes

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss/solrmarc-sw#166]
Minimally, add something to end of readme for any helpful dev environment setup notes here: https://docs.google.com/document/d/1jCj9rGKSqiDiSGKHaEnRApc77cwc7PpVE61thy-p9-s/edit#heading=h.bek409x1uvzc

Doesn't need to be finessed or polished, mainly don't want to lose any of these helpful notes on issues like java versions, ant installation, env variables in case of future utility.

**Comment by mejackreed** [comment]
Similar to @jkeck I'm good with the docs in there current format. Though I think some of this might change if #167 is merged/accepted.

**Comment by cmh2166** [comment]
Confirmed done / sufficient via slack.
