### ISSUE TITLE
Rerun SW index pipeline profiling test run

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss/solrmarc-sw#171]
Rerun SW index pipeline profiling test run with data on bodoni but indexing to `sw-solr-g` (instead of sul-solr collection)

**Comment by mejackreed** [comment]
Resolved. Notes in here: https://docs.google.com/document/d/1uYeGCdEmR-9IYKEgm2jVXY828baomiJc2KVBaBASAJE/edit#heading=h.9xri535adkcr
